git:
  depth: 2

branches:
  only:
  - master

language: node_js
node_js: "10"

addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages: libxkbfile-dev

os:
- linux
- windows
- osx

install:
- npm install -g yarn

script: 
- yarn

notifications:
  on_success: change
  on_failure: always
  on_start: never
